---
title: "music_terms"
format: html
editor: visual
---

## Music terms {.unnumbered}

| Term                                  | Description                                                                                                                                                                                                                                                                                                                                                                                      |
|---------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `audio recording`                     | fixation of sounds \[ISRC standard\]                                                                                                                                                                                                                                                                                                                                                             |
| `author`                              | The author of music or lyrics. Entitled to authors' right or copyright.                                                                                                                                                                                                                                                                                                                          |
| `composer`                            | The author of a musical work. Entitled to authors' right or copyright.                                                                                                                                                                                                                                                                                                                           |
| `lyricist`                            | The author of the text of a musical work, or a literary text that is arranged together with a musical work. Entitled to authors' right or copyright.                                                                                                                                                                                                                                             |
| `music video recording`               | fixation of sounds synchronized with pictures or moving pictures where (a) the fixed sounds are wholly or substantially a musical performance or (b) the *recording* (3.3) is intended for viewing in association with a recording of a musical performance. \[ISRC standard\]                                                                                                                   |
| `DSP` or `digital streaming platform` | Digital service providers (DSPs), or Digital Streaming Platforms are companies or organisations that provide access to services online. DSPs can provide access to music downloads, like Apple's iTunes Store, or access to streaming music like Spotify, or even provide satellite-delivered content such as SiriusXM in the USA.                                                               |
| `performer`                           | The performer of a musical work; in case of a sound recording, the performer whose performance is fixed in the recording. They may be entitled to neighbouring or sound recording copyrights.                                                                                                                                                                                                    |
| `producer`                            | The person or legal entity that produces the recorded fixation of the sound recording. They are entitled to neighbouring or sound recording copyrights.                                                                                                                                                                                                                                          |
| `rights management (organisations)`   | the function of managing the rights on behalf of rights owners. It can be companies whose sole purpose is to ensure that content that has been licensed has delivered royalties that are identified and accounted for. The role can be taken by collective management organisations or by private companies on behalf of songwriters, composers, performers, music publishers, or record labels. |
|                                       |                                                                                                                                                                                                                                                                                                                                                                                                  |

: Music terms and definitions {tbl-colwidths="\[25,75\]"}

## References {.unnumbered}
